/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/board': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Panel: tarjetas de varias paradas
     * @description Lo mismo que muestra la web: una tarjeta por línea y sentido, con sus próximas llegadas.
     */
    get: operations['board_api_v1_board_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Catálogo completo
     * @description Líneas, sentidos y paradas en una sola respuesta: lo que la web carga al arrancar.
     */
    get: operations['get_catalog_api_v1_catalog_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Estado del servicio
     * @description Versión, versión de la API y estado del origen. La web lo usa para detectar el servidor.
     */
    get: operations['health_api_v1_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/lines': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Líneas */
    get: operations['list_lines_api_v1_lines_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/lines/{line_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Una línea y sus sentidos */
    get: operations['get_line_api_v1_lines__line_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/lines/{line_id}/timetable': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Horario de hoy de una línea
     * @description Salidas de hoy desde la cabecera de cada sentido y la frecuencia por franjas. Son las horas
     *     de salida del primer punto de la línea, no las de paso por cada parada.
     */
    get: operations['line_timetable_api_v1_lines__line_id__timetable_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/lines/{line_id}/vehicles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Dónde están los autobuses de una línea
     * @description Última posición conocida de cada autobús de la línea, con su sentido y la parada a la que
     *     se dirige. Las posiciones de más de 3 minutos se descartan.
     */
    get: operations['line_vehicles_api_v1_lines__line_id__vehicles_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/stops': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Buscar paradas */
    get: operations['list_stops_api_v1_stops_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/stops/nearby': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Paradas cercanas */
    get: operations['nearby_stops_api_v1_stops_nearby_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/stops/{stop_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Una parada y sus sentidos */
    get: operations['get_stop_api_v1_stops__stop_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/stops/{stop_id}/arrivals': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Próximas llegadas a una parada
     * @description Llegadas de todas las líneas de la parada, de la más próxima a la más lejana.
     *
     *     Los datos se comparten entre todos los clientes y se renuevan como mucho cada
     *     `LOGRONO_BUS_ARRIVALS_TTL_S` segundos; la cabecera `X-Cache` dice si vienen de caché.
     */
    get: operations['stop_arrivals_api_v1_stops__stop_id__arrivals_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Arrival */
    Arrival: {
      /**
       * Aimed
       * Format: date-time
       */
      aimed: string;
      /** Cancelled */
      cancelled: boolean;
      /** Delay S */
      delay_s: number;
      direction: components['schemas']['Direction'] | null;
      /**
       * Expected
       * Format: date-time
       */
      expected: string;
      /** Headsign */
      headsign: string | null;
      /** Is Approximate */
      is_approximate: boolean;
      /** Is Realtime */
      is_realtime: boolean;
      /** Line Id */
      line_id: string;
      /** Minutes */
      minutes: number;
      /** Pattern Id */
      pattern_id: string | null;
      /** Stop Id */
      stop_id: string;
      /** Terminates */
      terminates: boolean;
      /** Vehicle Id */
      vehicle_id: string | null;
    };
    /** Board */
    Board: {
      /** Cards */
      cards: components['schemas']['Card'][];
      /**
       * Generated At
       * Format: date-time
       */
      generated_at: string;
      /** Stale */
      stale: boolean;
    };
    /**
     * BoardFormat
     * @enum {string}
     */
    BoardFormat: 'json' | 'text';
    /** Card */
    Card: {
      /** Arrivals */
      arrivals: components['schemas']['Arrival'][];
      /** Colour */
      colour: string;
      direction: components['schemas']['Direction'] | null;
      /** Headsign */
      headsign: string | null;
      /** Line Id */
      line_id: string;
      /** Line Label */
      line_label: string;
      /** Line Name */
      line_name: string;
      /** Stop Id */
      stop_id: string;
      /** Stop Name */
      stop_name: string;
      /** Text Colour */
      text_colour: string;
    };
    /** @enum {string} */
    CardOrder: 'seleccion' | 'linea' | 'llegada';
    /**
     * Catalog
     * @description Static network description: lines, their directions, and stops.
     *
     *     Lookups are indexed lazily (``cached_property`` writes straight into the instance ``__dict__``,
     *     so it works on a frozen dataclass without slots).
     */
    Catalog: {
      /**
       * Fetched At
       * Format: date-time
       */
      fetched_at: string;
      /** Lines */
      lines: components['schemas']['Line'][];
      /** Patterns */
      patterns: components['schemas']['Pattern'][];
      /** Stops */
      stops: components['schemas']['Stop'][];
    };
    /**
     * CircuitState
     * @enum {string}
     */
    CircuitState: 'closed' | 'open' | 'half_open';
    /** @enum {string} */
    Direction: 'asc' | 'desc';
    /**
     * DirectionTimetable
     * @description Today's service in one direction of a line.
     */
    DirectionTimetable: {
      /** Departures */
      departures: string[];
      direction: components['schemas']['Direction'];
      /** Headsign */
      headsign: string;
      /** Origin */
      origin: string;
      /** Pattern Id */
      pattern_id: string;
      /** Periods */
      periods: components['schemas']['ServicePeriod'][];
    };
    /** Health */
    Health: {
      /** Api Version */
      api_version: number;
      /** Library Version */
      library_version: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'degraded';
      upstream: components['schemas']['UpstreamHealth'];
      /** Version */
      version: string;
    };
    /** Line */
    Line: {
      /** Colour */
      colour: string;
      /** Id */
      id: string;
      /** Label */
      label: string;
      /** Name */
      name: string;
      /** Text Colour */
      text_colour: string;
    };
    /** LineDetail */
    LineDetail: {
      line: components['schemas']['Line'];
      /** Patterns */
      patterns: components['schemas']['Pattern'][];
    };
    /** LineTimetable */
    LineTimetable: {
      /** Directions */
      directions: components['schemas']['DirectionTimetable'][];
      /**
       * Generated At
       * Format: date-time
       */
      generated_at: string;
      /** Line Id */
      line_id: string;
      /** Service Date */
      service_date: string;
    };
    /** LineVehicles */
    LineVehicles: {
      /**
       * Generated At
       * Format: date-time
       */
      generated_at: string;
      /** Line Id */
      line_id: string;
      /** Vehicles */
      vehicles: components['schemas']['Vehicle'][];
    };
    /** NearbyStop */
    NearbyStop: {
      /** Distance M */
      distance_m: number;
      stop: components['schemas']['Stop'];
    };
    /**
     * Pattern
     * @description One direction of a line: the ordered list of stops a bus visits.
     */
    Pattern: {
      direction: components['schemas']['Direction'];
      /** Headsign */
      headsign: string;
      /** Id */
      id: string;
      /** Line Id */
      line_id: string;
      /** Origin */
      origin: string;
      /** Stop Ids */
      stop_ids: string[];
    };
    /**
     * Problem
     * @description RFC 9457 error body (``application/problem+json``). Branch on ``type``.
     */
    Problem: {
      /** Detail */
      detail?: string | null;
      /** Instance */
      instance: string;
      /** Request Id */
      request_id?: string | null;
      /** Status */
      status: number;
      /** Title */
      title: string;
      /** Type */
      type: string;
    };
    /**
     * ServicePeriod
     * @description A stretch of the day with a regular headway.
     */
    ServicePeriod: {
      /** First */
      first: string;
      /** Interval Max Min */
      interval_max_min: number;
      /** Interval Min */
      interval_min: number;
      /** Last */
      last: string;
    };
    /** Stop */
    Stop: {
      /** Id */
      id: string;
      /** Lat */
      lat: number;
      /** Line Ids */
      line_ids: string[];
      /** Lon */
      lon: number;
      /** Name */
      name: string;
    };
    /** StopArrivals */
    StopArrivals: {
      /** Arrivals */
      arrivals: components['schemas']['Arrival'][];
      /**
       * Generated At
       * Format: date-time
       */
      generated_at: string;
      /** Stop Id */
      stop_id: string;
    };
    /** StopDetail */
    StopDetail: {
      /** Patterns */
      patterns: components['schemas']['Pattern'][];
      stop: components['schemas']['Stop'];
    };
    /**
     * TimeStyle
     * @description How the text board writes each arrival.
     * @enum {string}
     */
    TimeStyle: 'minutos' | 'hora';
    /** UpstreamHealth */
    UpstreamHealth: {
      /** Catalog Fetched At */
      catalog_fetched_at: string | null;
      circuit: components['schemas']['CircuitState'];
    };
    /**
     * Vehicle
     * @description A bus on the road, as last reported.
     */
    Vehicle: {
      /** Delay S */
      delay_s: number;
      direction: components['schemas']['Direction'] | null;
      /** Id */
      id: string;
      /** Lat */
      lat: number;
      /** Line Id */
      line_id: string;
      /** Lon */
      lon: number;
      /** Next Stop Id */
      next_stop_id: string | null;
      /** Pattern Id */
      pattern_id: string | null;
      /**
       * Recorded At
       * Format: date-time
       */
      recorded_at: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  board_api_v1_board_get: {
    parameters: {
      query: {
        /** @description Selección del panel (como en la URL de la web), p. ej. `101-2d.5a~100-2a` */
        p: string;
        limit?: number;
        /** @description `text` para widgets de texto */
        format?: components['schemas']['BoardFormat'];
        /** @description `seleccion` (como en `p`), `linea` (por número) o `llegada` (la primera) */
        orden?: components['schemas']['CardOrder'];
        /** @description Con `format=text`: `minutos` (4, 12 min) o `hora` (18:04, 18:12), que sigue siendo cierta aunque el widget tarde en refrescarse */
        tiempo?: components['schemas']['TimeStyle'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Board'];
          'text/plain': unknown;
        };
      };
      /** @description Selección no válida */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parada o línea inexistente */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parámetros no válidos */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento ha cambiado de formato */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento no responde (ver `Retry-After`) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  get_catalog_api_v1_catalog_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Catalog'];
        };
      };
      /** @description Selección no válida */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parada o línea inexistente */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parámetros no válidos */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento ha cambiado de formato */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento no responde (ver `Retry-After`) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
      /** @description Selección no válida */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parada o línea inexistente */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parámetros no válidos */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento ha cambiado de formato */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento no responde (ver `Retry-After`) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  list_lines_api_v1_lines_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Line'][];
        };
      };
      /** @description Selección no válida */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parada o línea inexistente */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parámetros no válidos */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento ha cambiado de formato */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento no responde (ver `Retry-After`) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  get_line_api_v1_lines__line_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        line_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LineDetail'];
        };
      };
      /** @description Selección no válida */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parada o línea inexistente */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parámetros no válidos */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento ha cambiado de formato */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento no responde (ver `Retry-After`) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  line_timetable_api_v1_lines__line_id__timetable_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        line_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LineTimetable'];
        };
      };
      /** @description Selección no válida */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parada o línea inexistente */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parámetros no válidos */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento ha cambiado de formato */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento no responde (ver `Retry-After`) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  line_vehicles_api_v1_lines__line_id__vehicles_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        line_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LineVehicles'];
        };
      };
      /** @description Selección no válida */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parada o línea inexistente */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parámetros no válidos */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento ha cambiado de formato */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento no responde (ver `Retry-After`) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  list_stops_api_v1_stops_get: {
    parameters: {
      query?: {
        /** @description Nombre o número; sin acentos ni mayúsculas */
        q?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Stop'][];
        };
      };
      /** @description Selección no válida */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parada o línea inexistente */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parámetros no válidos */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento ha cambiado de formato */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento no responde (ver `Retry-After`) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  nearby_stops_api_v1_stops_nearby_get: {
    parameters: {
      query: {
        lat: number;
        lon: number;
        radius_m?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NearbyStop'][];
        };
      };
      /** @description Selección no válida */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parada o línea inexistente */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parámetros no válidos */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento ha cambiado de formato */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento no responde (ver `Retry-After`) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  get_stop_api_v1_stops__stop_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stop_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StopDetail'];
        };
      };
      /** @description Selección no válida */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parada o línea inexistente */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parámetros no válidos */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento ha cambiado de formato */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento no responde (ver `Retry-After`) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  stop_arrivals_api_v1_stops__stop_id__arrivals_get: {
    parameters: {
      query?: {
        /** @description Filtro de líneas y sentidos, p. ej. `2d.5a` (a=ida, d=vuelta, x=ambos) */
        lines?: string | null;
      };
      header?: never;
      path: {
        stop_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StopArrivals'];
        };
      };
      /** @description Selección no válida */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parada o línea inexistente */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Parámetros no válidos */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento ha cambiado de formato */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description El servicio del Ayuntamiento no responde (ver `Retry-After`) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
}
